# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 05:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20180629_0542'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReplyOuestionComments',
            new_name='ReplyQuestionComments',
        ),
    ]
