# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 16:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('pic', models.ImageField(upload_to='group_pic')),
                ('hidden', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupadmin', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='groupmembers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
