# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groups',
            old_name='Description',
            new_name='description',
        ),
    ]
