# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20180619_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='groups',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
